locationtech/geowave

geowave-ingest/src/main/resources/geowave-ingest-cmd-completion.sh
geowave-ingest/src/main/resources/geowave-ingest.sh
packaging/rpm/centos/6/SOURCES/bash_profile.sh
packaging/rpm/centos/6/SPECS/geowave.spec

Scripts needed to complete ticket #161 "Create a wrapper script for geowave-ingest"

Add geowave-ingest helper script with bash command completion

---

geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/AccumuloDataStore.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/query/AccumuloConstraintsQuery.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/util/AccumuloUtils.java
geowave-accumulo/src/test/java/mil/nga/giat/geowave/accumulo/AccumuloDataStoreStatsTest.java
geowave-accumulo/src/test/java/mil/nga/giat/geowave/accumulo/DeleteWriterTest.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/plugin/GeoWaveFeatureReader.java
geowave-vector/src/test/java/mil/nga/giat/geowave/vector/plugin/GeoWaveFeatureReaderTest.java

GEOWAVE-159

---

docs/pom.xml

incrementing version to 0.8.3

---

geowave-test/pom.xml
geowave-test/src/main/java/mil/nga/giat/geowave/test/GeoWaveDFSTestEnvironment.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/GeoWaveTestEnvironment.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/mapreduce/MapReduceTestEnvironment.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/service/ServicesTestEnvironment.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/GeoWaveBasicIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/GeoWaveITSuite.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/mapreduce/BasicMapReduceIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/mapreduce/KDEMapReduceIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/mapreduce/MapReduceTestBase.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/service/GeoServerIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/service/GeoWaveServicesIT.java
pom.xml
tools/eclipse/eclipse-formatter.xml

Also attempt to cleanup mapreduce logspam, and add (optional) HDFS local cluster
#213

refactoring test environments into src to be reusable

---

geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/AccumuloOperations.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/BasicAccumuloOperations.java
geowave-accumulo/src/test/java/mil/nga/giat/geowave/accumulo/AccumuloOptionsTest.java
geowave-benchmark/src/main/java/mil/nga/giat/geowave/benchmark/FeatureCollectionDataAdapterBenchmark.java
geowave-ingest/src/main/java/mil/nga/giat/geowave/ingest/AccumuloCommandLineOptions.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/GeoWaveTestEnvironment.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/GeoWaveBasicIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/mapreduce/BasicMapReduceIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/mapreduce/KDEMapReduceIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/service/GeoServerIT.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/service/GeoWaveServicesIT.java

Handle no tables added case

---

.travis.yml
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce/NativeMapContext.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce/NativeReduceContext.java
pom.xml

Create separate build profiles for Apache (default), Hortonworks (-P horonworks), and Cloudera (-P cloudera) distributions.
Addresses issue #241.

Build against Apache Hadoop

---

geowave-store/src/main/java/mil/nga/giat/geowave/store/data/field/BasicReader.java
geowave-store/src/main/java/mil/nga/giat/geowave/store/data/field/BasicWriter.java
geowave-store/src/main/java/mil/nga/giat/geowave/store/data/field/FieldUtils.java
geowave-test/src/test/java/mil/nga/giat/geowave/test/GeoWaveBasicIT.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/adapter/FeatureDataAdapter.java
pom.xml

Breaks BigDecimal persistence, but looks like it wasn't working before anyway

Fixed BigDecimal readers/writers to properly serialize values, registered missing writers/readers, added integration test

---

.travis.yml
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/AccumuloDataStore.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/mapreduce/input/GeoWaveInputFormat.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/query/ElementsToArrayIterator.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/util/AccumuloUtils.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/util/IteratorWrapper.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/util/StatsTool.java
geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/DensityProcess.java
geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/mapreduce/kde/KDEJobRunner.java
geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/tools/AnalyticFeature.java
geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/tools/GeometryDataSetGenerator.java
geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/tools/PropertyManagement.java
geowave-raster/src/main/java/mil/nga/giat/geowave/raster/RasterUtils.java
geowave-raster/src/main/java/mil/nga/giat/geowave/raster/adapter/merge/nodata/NoDataMergeStrategy.java
geowave-raster/src/main/java/mil/nga/giat/geowave/raster/adapter/merge/nodata/NoDataMetadataFactory.java
geowave-raster/src/main/java/mil/nga/giat/geowave/raster/resize/RasterTileResizeJobRunner.java
geowave-services/src/main/java/mil/nga/giat/geowave/services/impl/GeoserverServiceImpl.java
geowave-store/src/main/java/mil/nga/giat/geowave/store/adapter/statistics/DataStatisticsBuilder.java
geowave-store/src/main/java/mil/nga/giat/geowave/store/adapter/statistics/StatsCompositionTool.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/GeoWaveTestEnvironment.java
geowave-test/src/main/java/mil/nga/giat/geowave/test/mapreduce/MapReduceTestEnvironment.java
geowave-types/src/main/java/mil/nga/giat/geowave/types/geolife/GeoLifeIngestPlugin.java
geowave-utils/src/main/java/mil/nga/giat/geowave/utils/GeowaveUtils.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/adapter/FeatureCollectionDataAdapter.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/plugin/transaction/GeoWaveTransactionManagement.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/util/FeatureCollectionRedistributor.java

(don't accept this yet, wanted to open this up to discuss a few questions first)
(coverity issues can be seen @ https://scan.coverity.com/projects/3371/view_defects - login required)

Fixes for coverity id'd issues

---

.travis.yml
.utility/changelog-generator.sh
pom.xml

This should - on commits to master - automatically generate a changelog and post it to http://ngageoint.github.io/geowave/CHANGELOG.md
@spohnan 
think this one is in your wheelhouse to review - as I type this I realize if it outputs MD we probably want to render that to html for the page.

Add: Added in changelog auto generation

---

docs/pom.xml
geowave-accumulo/pom.xml
geowave-analytics/pom.xml
geowave-benchmark/pom.xml
geowave-client/pom.xml
geowave-deploy/pom.xml
geowave-examples/pom.xml
geowave-index/pom.xml
geowave-ingest/pom.xml
geowave-raster/pom.xml
geowave-services/pom.xml
geowave-store/pom.xml
geowave-test/pom.xml
geowave-types/pom.xml
geowave-utils/pom.xml
geowave-vector/pom.xml
pom.xml

release v0.8.4

---

geowave-vector/src/test/java/mil/nga/giat/geowave/vector/plugin/GeoWaveFeatureReaderTest.java

GEOWAVE-350

---

docs/content/085-accumulo-config.adoc
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/AccumuloOperations.java
geowave-accumulo/src/main/java/mil/nga/giat/geowave/accumulo/BasicAccumuloOperations.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/plugin/GeoWaveGTDataStore.java
geowave-vector/src/main/java/mil/nga/giat/geowave/vector/transaction/ZooKeeperTransactionsAllocater.java
geowave-vector/src/test/java/mil/nga/giat/geowave/vector/plugin/GeoWaveGTMemDataStore.java
geowave-vector/src/test/java/mil/nga/giat/geowave/vector/plugin/MemoryTransactionsAllocater.java

#352 
Command line tool adjusted to take -r (for recipient) argument to allocate transaction ids for the specific user.

GEOWAVE-352

---

examples/src/main/java/mil/nga/giat/geowave/examples/ingest/bulk/GeonamesDataFileInputFormat.java
examples/src/main/java/mil/nga/giat/geowave/examples/ingest/bulk/GeonamesSimpleFeatureType.java
examples/src/main/java/mil/nga/giat/geowave/examples/ingest/bulk/SimpleFeatureToAccumuloKeyValueMapper.java
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/util/AccumuloKeyValuePair.java
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/util/AccumuloKeyValuePairGenerator.java
test/src/test/java/mil/nga/giat/geowave/test/mapreduce/BulkIngestInputGenerationIT.java
test/src/test/resources/mil/nga/giat/geowave/test/geonames/barbados/BB.txt
test/src/test/resources/mil/nga/giat/geowave/test/geonames/readme.txt

Implementation for #157 ...
The crux of the solution is within `AccumuloKeyValuePairGenerator` which produces Accumulo [Key,Value] pairs (Geowave-formatted) given an adapter and an index, similar to the way we currently produce Mutations.
To fully demonstrate the "flow" of this solution, I created an example MapReduce job that:
1. reads in some sample Geonames data (downloaded a bunch of points in Barbados)
2. constructs SimpleFeatures for the sample data
3. leverages AccumuloKeyValuePairGenerator to generate [Key,Value] pairs
4. writes the data to file using AccumuloFileOutputFormat (after MapReduce sorts the [Key,Value] pairs) 
Feedback welcome!

GEOWAVE-157

---

dev-resources/pom.xml
pom.xml

* geowave-dev-resources will now publish to the s3 maven repositories for geowave
* geowave adds the geowave s3 maven repos as a dependency

geowave-dev-resources to maven

---

examples/src/main/java/mil/nga/giat/geowave/examples/query/GeotoolsQueryExample.java

GeoTools query example for #116

Added GeoTools query example

---

test/src/test/java/mil/nga/giat/geowave/test/service/GeoWaveIngestGeoserverIT.java

#392 
Looks like the rendering changes actually made it in in 2.6.2

fix to wms test

---

extensions/formats/geolife/src/main/resources/META-INF/services/mil.nga.giat.geowave.core.ingest.IngestFormatPluginProviderSpi

SPI classname update

---

analytics/api/pom.xml
analytics/mapreduce/pom.xml
analytics/pom.xml
core/cli/pom.xml
core/geotime/pom.xml
core/index/pom.xml
core/ingest/pom.xml
core/pom.xml
core/store/pom.xml
deploy/pom.xml
docs/pom.xml
examples/pom.xml
extensions/adapters/raster/pom.xml
extensions/adapters/vector/pom.xml
extensions/datastores/accumulo/pom.xml
extensions/formats/geolife/pom.xml
extensions/formats/geotools-raster/pom.xml
extensions/formats/geotools-vector/pom.xml
extensions/formats/gpx/pom.xml
extensions/formats/tdrive/pom.xml
extensions/pom.xml
pom.xml
services/api/pom.xml
services/client/pom.xml
services/pom.xml
services/webapp/pom.xml
test/pom.xml

Updates for 0.8.7 release

---

core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/statistics/BoundingBoxDataStatistics.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/adapter/statistics/NumericRangeDataStatistics.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/FeatureDataAdapter.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureBoundingBoxStatistics.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureFixedBinNumericStatistics.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureNumericRangeStatistics.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/utils/SimpleFeatureUserDataConfigurationSet.java

The 7 files in this commit are currently incorrectly formatted in the repository, so these files show up as dirty as a result of a full build that does not specify the -DskipFormat=true flag.

Formatting Fixes

---

extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/cli/StatsOperation.java

Just fixed the logger initialization.

Fixed the logger initialization

---

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/CompoundIngestFormatOptionProvider.java
extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/GeoToolsVectorDataStoreIngestFormat.java
extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/retyping/date/DateFieldOptionProvider.java
extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/retyping/date/DateFieldRetypingPlugin.java
extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/retyping/date/DateFieldRetypingSource.java

Adds Date retyping for GeoTools Vector ingest (#468).  To support it, adds CompoundIngestFormatOptionProvider to enable multiple providers for a single ingest plugin.

Adds Date retyping for GeoTools Vector ingest (#468)

---

deploy/packaging/rpm/admin-scripts/jenkins-build-geowave.sh
deploy/packaging/rpm/centos/6/SPECS/geowave.spec
deploy/packaging/rpm/centos/6/rpm.sh
docs/content/062-analyticsoverview.adoc

Some fixes to packaging and docs added to the 0.8.8.1 release that need to be carried forward as well.

Package analytics jar and fix doc markup

---

analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDEJobRunner.java

Enables KDEJobRunner to add JARs to Job classpath from configured array of HDFS paths

---

analytics/api/pom.xml
analytics/mapreduce/pom.xml
analytics/pom.xml
core/cli/pom.xml
core/geotime/pom.xml
core/index/pom.xml
core/ingest/pom.xml
core/pom.xml
core/store/pom.xml
deploy/pom.xml
docs/pom.xml
examples/pom.xml
extensions/adapters/raster/pom.xml
extensions/adapters/vector/pom.xml
extensions/datastores/accumulo/pom.xml
extensions/formats/geolife/pom.xml
extensions/formats/geotools-raster/pom.xml
extensions/formats/geotools-vector/pom.xml
extensions/formats/gpx/pom.xml
extensions/formats/stanag4676/format/pom.xml
extensions/formats/stanag4676/service/pom.xml
extensions/formats/tdrive/pom.xml
extensions/pom.xml
pom.xml
services/api/pom.xml
services/client/pom.xml
services/pom.xml
services/webapp/pom.xml
test/pom.xml

0.8.9 release version bump

---

analytics/api/pom.xml
analytics/mapreduce/pom.xml
analytics/pom.xml
core/cli/pom.xml
core/geotime/pom.xml
core/index/pom.xml
core/ingest/pom.xml
core/pom.xml
core/store/pom.xml
deploy/pom.xml
docs/pom.xml
examples/pom.xml
extensions/adapters/raster/pom.xml
extensions/adapters/vector/pom.xml
extensions/datastores/accumulo/pom.xml
extensions/formats/geolife/pom.xml
extensions/formats/geotools-raster/pom.xml
extensions/formats/geotools-vector/pom.xml
extensions/formats/gpx/pom.xml
extensions/formats/stanag4676/format/pom.xml
extensions/formats/stanag4676/service/pom.xml
extensions/formats/tdrive/pom.xml
extensions/pom.xml
pom.xml
services/api/pom.xml
services/client/pom.xml
services/pom.xml
services/webapp/pom.xml
test/pom.xml

Roll to 0.9.0-SNAPSHOT for continued development

0.9.0-SNAPSHOT version bump

---

examples/src/main/java/mil/nga/giat/geowave/examples/query/SpatialQueryExample.java

Just adding some examples we found useful to learn/understand.

Some ingesting and querying use case examples.

---

deploy/emr/4/bootstrap-geowave.sh
deploy/emr/4/geowave-install-lib.sh
deploy/emr/README.md
docs/content/081-running-from-emr.adoc

This commit provides an initial capability to run GeoWave within an AWS EMR cluster in response to #551

Initial Deploy GeoWave to EMR capability

---

core/geotime/pom.xml
core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/filter/SpatialQueryFilter.java
pom.xml

Fix for #583.  Also backs out of temporary fix for #564.  I used the [FilterTest](https://github.com/ngageoint/geowave/files/98162/FilterTest.java.txt) provided by @datasedai to verify.

Upgrade to JTS v1.14

---

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureCollection.java

this is what appears to be a bug @dcy2003 pointed out in what I just merged (sorry)

simple fix to limits

---

core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/index/dimension/TemporalBinningStrategy.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/index/dimension/TemporalBinningStrategyTest.java

just a simple additional check - doesn't seem to be an issue or anything, just seemed appropriate/consistent behavior

added extra check for end less than start before calculating bins

---

README.md

Updated supported version #s of core libraries

---

analytics/api/src/main/java/mil/nga/giat/geowave/analytic/PropertyManagement.java
core/index/src/main/java/mil/nga/giat/geowave/core/index/PersistenceUtils.java

Protect against NPE

---

extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/AccumuloDataStore.java
test/src/test/java/mil/nga/giat/geowave/test/GeoWaveITSuite.java
test/src/test/java/mil/nga/giat/geowave/test/query/PolygonDataIdQueryIT.java

Fix to properly deduplicate results from DataIdQuery

---

core/store/src/main/java/mil/nga/giat/geowave/core/store/data/CommonIndexedPersistenceEncoding.java

for wholefeaturedataadapter, getCommonData returns null which causes an npe with line/poly/time range data here

fixed a npe if common data is null

---

extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/resize/RasterOperationCLIProvider.java
extensions/adapters/raster/src/main/resources/META-INF/services/mil.nga.giat.geowave.core.cli.CLIOperationProviderSpi

GEOWAVE-679: raster resize CLI fix

---

docs/content/005-about.adoc
docs/content/035-adapters.adoc
docs/content/050-tools-framework.adoc
docs/content/107-contributions

Moved pull request section from About to a new Contribution section.
Also removed redundant text on statistics in adapters section (was an
exact dup of statistics section), and also minor tech edits.

Added Contribution Section to Docs

---

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/query/cql/CQLQueryFilter.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/query/cql/FilterToCQLTool.java
extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/query/cql/FilterToCQLToolTest.java
test/src/test/java/mil/nga/giat/geowave/test/query/SpatialTemporalQueryIT.java

Geowave 653

---

docs/content/050-tools-framework.adoc
docs/content/062-analyticsoverview.adoc
docs/content/080-install-from-source.adoc
docs/content/090-building.adoc

Add new required arg to doc examples

GEOWAVE-713: Add accumulo.api argument to doc examples

---

extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/mapreduce/HBaseMRUtils.java
extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/query/HBaseFilteredIndexQuery.java
extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/query/InputFormatHBaseRangeQuery.java
extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/util/HBaseUtils.java
test/src/main/java/mil/nga/giat/geowave/test/TestUtils.java

Further fixes from mapreduce testing

---

core/cli/pom.xml
core/geotime/pom.xml
core/index/pom.xml
core/mapreduce/pom.xml
core/store/pom.xml
extensions/formats/stanag4676/service/pom.xml

Use JUnit 4.11 rather than various conflicting versoins

---

core/cli/pom.xml
core/geotime/pom.xml
core/index/pom.xml
core/mapreduce/pom.xml
core/store/pom.xml
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AttributeSubsettingIterator.java
extensions/formats/stanag4676/service/pom.xml

Subset fields after filtering, rather than prior (performance improvement)

---

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWavePluginConfig.java
test/src/main/java/mil/nga/giat/geowave/test/GeoWaveITRunner.java
test/src/main/java/mil/nga/giat/geowave/test/service/ServicesTestEnvironment.java

- Fix IT to actually tearDown(), bug introduced earlier
- Fix GeoServerIT to properly setup WFS

GEOWAVE-668 - Resolve Namespace issues

---

analytics/api/src/main/java/mil/nga/giat/geowave/analytic/param/BasicParameterHelper.java
analytics/api/src/main/java/mil/nga/giat/geowave/analytic/param/InputStoreParameterHelper.java
analytics/api/src/main/java/mil/nga/giat/geowave/analytic/param/OutputStoreParameterHelper.java
analytics/api/src/main/java/mil/nga/giat/geowave/analytic/param/ParameterHelper.java
analytics/api/src/test/java/mil/nga/giat/geowave/analytic/PropertyManagementTest.java
analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/operations/options/PropertyManagementConverter.java
core/index/src/main/java/mil/nga/giat/geowave/core/index/sfc/zorder/ZOrderUtils.java
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/AccumuloMRUtils.java
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AttributeSubsettingIterator.java
test/src/main/java/mil/nga/giat/geowave/test/service/ServicesTestEnvironment.java

Added to fix issue where analytics properties do not set correctly from the command line.   Already added to 0.9.1 tag.

GEOWAVE-546 - Fix issue with Analytics

---

docs/content/042-toolsframework.adoc

GEOWAVE-739 - Add documentation for the version, debug, help, explain

---

core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/index/dimension/TemporalBinningStrategy.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/index/dimension/TemporalBinningStrategyTest.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/index/dimension/TimeDefinitionTest.java

added temporal units to support binning by decade, hour, and minute

---

docs/content/062-analyticsoverview.adoc
docs/content/manpages/geowave-rmstat.txt

Fixes small formatting problem in rmstat options and also corrects the
callout problem in analytics overview by correcting note formatting.

GEOWAVE-812

---

extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/AccumuloDataStore.java

looks like there's some reformatting happening as well

GEOWAVE-809: row ID query support for a list of IDs

---

extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloConstraintsQuery.java
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AggregationIterator.java

Fixed two bugs that were stopping statistics from populating

Fixed errors in AccumuloConstraints Query and AggregationIterator

---

core/mapreduce/src/main/java/mil/nga/giat/geowave/mapreduce/output/GeoWaveOutputFormat.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/GeoWaveStoreFinder.java
dev-resources/pom.xml
extensions/formats/gpx/src/test/resources/sample_gpx.xml
extensions/formats/stanag4676/service/pom.xml
extensions/formats/stanag4676/service/src/main/java/mil/nga/giat/geowave/types/stanag4676/service/rest/Stanag4676ImageryChipService.java
extensions/formats/stanag4676/service/src/main/resources/geoserver_files/colormap.sld
extensions/formats/stanag4676/service/src/main/resources/geoserver_files/config.xml
extensions/pom.xml

#829 #828 
Replaced the xuggler library with jcodec.  Updated files to support 4676 data ingest and display.

Geowave 829

---

deploy/emr/4/gdelt-example/bootstrap-geowave.sh
deploy/emr/4/gdelt-example/geowave-env.sh
deploy/emr/4/gdelt-example/geowave-install-lib.sh
deploy/emr/4/gdelt-example/ingest-and-kde-gdelt.sh
deploy/emr/4/gdelt-example/setup-geoserver-geowave-workspace.sh

Made some small changes to the gdelt-example for use with the new geowave quickstart guide.

Changes for the quick-start guide scripts

---

core/cli/src/main/java/mil/nga/giat/geowave/core/cli/operations/config/options/ConfigOptions.java

This change should allow the program to use any available config.properties file even if it runs into an issue with getting the geowave version.

Geowave 833

---

test/pom.xml

...and removed cli-stats which no longer exists

added geoserver cli to jacoco source directories

---

deploy/emr/4/dev/bootstrap-geowave-accumulo.sh
deploy/emr/4/dev/bootstrap-geowave.sh
deploy/emr/4/release/bootstrap-geowave-accumulo.sh
deploy/emr/4/release/bootstrap-geowave.sh

Changed the bootstrap scripts get the geowave-install-lib.sh from a geowave downloads bucket.

GEOWAVE 833-2

---

deploy/pom.xml
examples/src/main/java/mil/nga/giat/geowave/examples/hbase/HBaseMiniCluster.java
extensions/cli/geoserver/src/main/java/mil/nga/giat/geowave/cli/geoserver/GeoServerRestClient.java

Fix missing HBase impl for GeoServer add datastore;  
don't exclude guava for GS singlejar;  
add HBase minicluster example

Fix missing HBase impl for GeoServer CLI

---

examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestIndexWriter.java
examples/src/main/java/mil/nga/giat/geowave/examples/query/CQLQueryExample.java

Fixed SimpleIngestIndexWriter example to index command line arguments correctly

Fixed incorrect indexing of the command line arguments

---

core/cli/src/test/java/mil/nga/giat/geowave/core/cli/VersionUtilsTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/ExplainCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/HelpCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/ListCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/SetCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/options/ConfigOptionsTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/spi/OperationRegistryTest.java

unit tests added for GeoWaveMain, VersionUtils, ExplainCommand, HelpCommand, ListCommand, SetCommand, ConfigOptions, and OperationRegistry

GeoWave Issue #1006

---

extensions/cli/geoserver/pom.xml
extensions/cli/geoserver/src/main/java/mil/nga/giat/geowave/cli/geoserver/GeoServerRestClient.java
extensions/cli/geoserver/src/test/java/mil/nga/giat/geowave/cli/geoserver/GeoServerRestClientTest.java
test/pom.xml

Adds tests verifying correct path is requested on most get* and add* methods for GeoServerRestClient.java

Issue #998

---

extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/DynamoDBWriter.java

Added support using async handler for batchWrite and PutItem. On flush, the pending async requests are waited on for and completed.

Issue[1024] Add support for asynchronous query of bulk ingest. 

---

core/cli/src/test/java/mil/nga/giat/geowave/core/cli/prefix/JavassistUtilsTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/prefix/PrefixedJCommanderTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/prefix/TranslationEntryTest.java

Add new tests for JavassistUtils, PrefixedJCommander, TranslationEntry classes
Issue #1005

Add unit tests for classes in mil.nga.giat.geowave.core.cli.prefix

---

core/mapreduce/src/main/java/mil/nga/giat/geowave/mapreduce/splits/IntermediateSplitInfo.java
extensions/datastores/accumulo/pom.xml
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/AccumuloSplitsProvider.java
extensions/datastores/accumulo/src/test/java/mil/nga/giat/geowave/datastore/accumulo/mapreduce/AccumuloSplitsProviderTest.java

Commit changes for Accumulo SplitsProvider tests as one commit Tests populateIntermediateSplits, wrapRange and unwrapRange

Issue #1001 - Testing AccumuloSplitsProvider

---

core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/filter/SpatialQueryFilter.java
core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialQuery.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/BasicQueryTest.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialQueryTest.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialTemporalQueryTest.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/filter/BasicQueryFilter.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/query/BasicQuery.java
core/store/src/test/java/mil/nga/giat/geowave/core/store/filter/DistributedQueryFilterTest.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/query/cql/CQLQuery.java

This fixes issue #1011 by adding all the geometric compare operators defined in DE-9IM

Added geometric compare operations for Geometric objects and 1D data

---

core/cli/src/test/java/mil/nga/giat/geowave/core/cli/VersionUtilsTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/ExplainCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/HelpCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/ListCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/SetCommandTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/operations/config/options/ConfigOptionsTest.java
core/cli/src/test/java/mil/nga/giat/geowave/core/cli/spi/OperationRegistryTest.java
core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/filter/SpatialQueryFilter.java
core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialQuery.java
core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialTemporalQuery.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/BasicQueryTest.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialQueryTest.java
core/geotime/src/test/java/mil/nga/giat/geowave/core/geotime/store/query/SpatialTemporalQueryTest.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/filter/BasicQueryFilter.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/query/BasicQuery.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/ExtractGeometryFilterVisitor.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/ExtractGeometryFilterVisitorResult.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureCollection.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/query/cql/CQLQuery.java
extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/plugin/ExtractGeometryFilterVisitorTest.java
extensions/cli/landsat8/src/main/java/mil/nga/giat/geowave/format/landsat8/RasterIngestRunner.java

Added capability to retain geometric predicate associated with query geometry extracted from CQL expression

---

extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/CassandraDataStore.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/mapreduce/CassandraRangeLocatorPair.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/mapreduce/CassandraRowRange.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/mapreduce/GeoWaveCassandraInputSplit.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/mapreduce/GeoWaveCassandraRecordReader.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/query/InputFormatCassandraRangeQuery.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/split/CassandraSplitsProvider.java
extensions/datastores/cassandra/src/main/java/mil/nga/giat/geowave/datastore/cassandra/util/CassandraInputFormatIteratorWrapper.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/DynamoDBDataStore.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/mapreduce/DynamoDBRangeLocatorPair.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/mapreduce/DynamoDBRowRange.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/mapreduce/GeoWaveDynamoDBInputSplit.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/mapreduce/GeoWaveDynamoDBRecordReader.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/query/InputFormatDynamoDBRangeQuery.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/split/DynamoDBSplitsProvider.java
extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/util/DynamoDBInputFormatIteratorWrapper.java
test/src/main/java/mil/nga/giat/geowave/test/DynamoDBLocal.java
test/src/test/java/mil/nga/giat/geowave/test/mapreduce/BasicMapReduceIT.java

This is for both DynamoDB and Cassandra; I'll add the adapter id changes in a separate change, as there were complications with that commit
Note: The previous pull request I had was on a different branch, how can I close that pull request?

Ap casanamo mapreduce cassandra

---

analytics/javaspark/src/main/java/mil/nga/giat/geowave/analytic/javaspark/sparksql/operations/SparkSqlCommand.java
analytics/javaspark/src/main/java/mil/nga/giat/geowave/analytic/javaspark/sparksql/operations/SparkSqlOptions.java

Last-minute improvements for SparkSQL impl.

Added CSV output; improved temp naming

---

core/cli/src/main/java/mil/nga/giat/geowave/core/cli/Constants.java
core/cli/src/main/java/mil/nga/giat/geowave/core/cli/operations/config/SetCommand.java
core/cli/src/main/java/mil/nga/giat/geowave/core/cli/operations/config/options/ConfigOptions.java

…ibuted cluster can be resolved

Encryption Fix

---

deploy/Jenkinsfile
deploy/packaging/docker/docker-build-rpms.sh

Fixed indents in the jenkinsfile that is why every line is modified. Also stage to upload cache to `s3://geowave/mvn-cache/`

Tar cache and upload to s3.

---

deploy/packaging/docker/build-rpm/build-rpm.sh
deploy/packaging/docker/build-src/build-geowave-common.sh
deploy/packaging/docker/build-src/build-geowave-vendor.sh
deploy/packaging/docker/docker-build-rpms.sh
deploy/packaging/docker/publish/publish-common-rpm.sh
deploy/packaging/docker/publish/publish-vendor-rpm.sh

Proper error handling when scripts crash. Directories will now be cleared properly on new Jenkins jobs.

Changing error

---

deploy/packaging/rpm/centos/7/SOURCES/geowave-tools.sh
deploy/pom.xml
deploy/src/main/resources/log4j.properties

Signed-off-by: Srinivas Varala <srinivas.varala@gmail.com>

Modified geowave tools script

---

services/rest/pom.xml

merged spring files together and included slf4j

fixes for service deployment

---

services/rest/src/main/java/mil/nga/giat/geowave/service/rest/security/GeoWaveSQLiteApiKeyDB.java

Fixes for Improper Resource Shutdown or Release

Addressed Threadfix true-positives for REST webapp

---

deploy/pom.xml
extensions/datastores/hbase/pom.xml
pom.xml
services/rest/pom.xml

fixed geoserver-cdh-hbase dependency and servlet dependencies

---

docs/content/commands/000-titlepage.adoc
docs/content/devguide/000-titlepage.adoc
docs/content/userguide/000-titlepage.adoc

Updating links in documentation to packages and asciidocs so they are version-specific, rather than always going to the latest documentation.

Updating packages and asciidocs links in documentation

---

analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/operations/DBScanCommand.java
analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/operations/KdeCommand.java
analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/operations/NearestNeighborCommand.java
core/cli/src/main/java/mil/nga/giat/geowave/core/cli/api/ServiceEnabledCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/KafkaToGeowaveCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToGeowaveCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToHdfsCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToKafkaCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToMapReduceToGeowaveCommand.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/MapReduceToGeowaveCommand.java
services/rest/pom.xml
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/ApiRestletApplication.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/AsyncOperationStatusResource.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/FileUploadResource.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/GeoWaveOperationServiceWrapper.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/operations/RestOperationStatusMessage.java

This work includes updates to ServiceEnabledCommand (and classes that derive from it) to provide a hint to services on whether the operation should be run sync/async.

Provided status endpoint for REST operations and return data in JSON format

---

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/IngestUtils.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/hdfs/HdfsUrlStreamHandlerFactory.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/local/AbstractLocalFileDriver.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/spark/SparkIngestIngestDriver.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/operations/remote/options/StoreLoader.java
extensions/datastores/accumulo/pom.xml
extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/util/AccumuloUtils.java

Fix for Accumulo WFS w/ CQL killing tablet server; fix for bad storeloader config init

HDFS URL stream handler; storeloader config

---

deploy/pom.xml
extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/adapter/RasterDataAdapter.java
extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/operations/BasicHBaseOperations.java
extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/query/HBaseConstraintsQuery.java

Fix(es) for HBase failing to register the aggregation coprocessor when WFS request includes CQL filter. Also provides failover to client-side aggregation when coprocessor registration fails.

Improve coprocessor registration and error handling

---

deploy/Jenkinsfile
deploy/packaging/docker/build-rpm/build-services-rpm.sh

Change geoserver version into a variable to make future geoserver version upgrades easier

Update geoserver version

---

deploy/packaging/docker/build-rpm/deploy-geowave-to-hdfs.sh.template

This should Detect if aws is installed, check the hbase site config, and if it is using s3, attempt to copy the Java library over.

Copy Java library to s3 when needed

---

deploy/packaging/emr/template/bootstrap-jupyter.sh.template
examples/data/notebooks/jupyter/geowave-gdelt.ipynb
examples/data/notebooks/jupyter/geowave-gpx.ipynb
examples/data/notebooks/jupyter/geowave-spatial-join.ipynb

Changes notebooks slightly to better support running from same cluster, and fixes small missing dependency issue within gpx/gdelt notebooks that I thought was handled but missed.

Small fixes to changes to master notebooks and jupyter bootstrap for release

---

core/mapreduce/src/main/java/mil/nga/giat/geowave/mapreduce/splits/SplitsProvider.java
deploy/src/main/resources/log4j.properties
test/src/test/resources/log4j-test.properties

Splits provider fix to continue splitting after first failure at highest cardinality.

Splits provider fix to continue splitting after first failure

---

analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/GeoWaveIndexedRDD.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/GeoWaveRDDLoader.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/GeoWaveRegistrator.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/RDDUtils.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/sparksql/udf/GeomFunction.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/sparksql/udf/wkt/WKTGeomFunction.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/spatial/SpatialJoinRunner.java
analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/spatial/TieredSpatialJoin.java
core/index/src/main/java/mil/nga/giat/geowave/core/index/sfc/tiered/TieredSFCIndexStrategy.java
extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/util/FeatureDataUtils.java
test/src/test/resources/log4j-test.properties

Changes include trimming insertion keys, and reducing overall algorithm stages.

Optimizations to spatial join for other geometry types.

---

analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDEJobRunner.java
analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDEReducer.java
core/index/src/main/java/mil/nga/giat/geowave/core/index/FloatCompareUtils.java
core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/ListPluginsCommand.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/cli/config/AddIndexCommand.java
core/store/src/main/java/mil/nga/giat/geowave/core/store/cli/config/AddStoreCommand.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/GeoWaveOperationFinder.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/GeoWaveOperationServiceWrapper.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/field/AbstractMainParam.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/field/ParameterRestField.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/field/ParameterRestFieldValue.java
services/rest/src/main/java/mil/nga/giat/geowave/service/rest/field/RestFieldValue.java

KDERasterResizeIT has been failing periodically, and its due to the double comparison as described in KDEReducer changes in this PR

formatting changes and kde fix

---

docs/content/commands/065-services-commands.adoc
docs/content/commands/manpages/services/geowave-grpc-start.txt
docs/content/commands/manpages/services/geowave-grpc-stop.txt
docs/content/devguide/069-services.adoc

Added sections for CLI commands and overview in Dev guide

Added docs for gRPC

---

deploy/packaging/emr/generate-emr-scripts.sh
deploy/packaging/emr/template/jupyter/bootstrap-jupyter.sh.template
deploy/packaging/emr/template/jupyter/bootstrap-jupyterhub.sh.template
deploy/packaging/emr/template/jupyter/gw-base.yml
deploy/packaging/emr/template/jupyter/install-conda.sh
deploy/packaging/emr/template/jupyter/pre-spawn.sh

and fix user who creates hdfs home directory.

Install all dependencies through conda environment yml file

---

analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/spatial/SpatialJoinRunner.java
examples/data/notebooks/jupyter/geowave-spatial-join.ipynb

fixes code path error, not caught by tests.

spatial join patch.

---

core/index/src/main/java/org/locationtech/geowave/core/index/IndexUtils.java
core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseFilteredIndexQuery.java
core/store/src/main/java/org/locationtech/geowave/core/store/util/NativeEntryIteratorWrapper.java
examples/java-api/src/main/java/org/locationtech/geowave/examples/ingest/SimpleIngest.java
extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveDataStoreComponents.java
extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveFeatureReader.java
extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveGTDataStore.java
extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/SubsampleProcess.java
extensions/datastores/hbase/src/main/java/org/locationtech/geowave/datastore/hbase/filters/FixedCardinalitySkippingFilter.java
extensions/datastores/hbase/src/main/java/org/locationtech/geowave/datastore/hbase/operations/HBaseReader.java
test/src/test/java/org/locationtech/geowave/test/services/GeoServerIngestIT.java

Fix issues where valid features would sometimes get excluded by the subsampling filter.
Fix issue where HBase subsampling filter would not seek to the next valid row.
Fix exception when querying a spatial index with a temporal constraint.

Fix issues with subsampling

---

analytics/spark/src/main/java/org/locationtech/geowave/analytic/spark/kmeans/KMeansRunner.java
analytics/spark/src/main/java/org/locationtech/geowave/analytic/spark/kmeans/operations/KmeansSparkCommand.java
analytics/spark/src/main/java/org/locationtech/geowave/analytic/spark/sparksql/operations/SparkSqlCommand.java
analytics/spark/src/main/java/org/locationtech/geowave/analytic/spark/spatial/SpatialJoinRunner.java
analytics/spark/src/main/java/org/locationtech/geowave/analytic/spark/spatial/operations/SpatialJoinCommand.java
core/ingest/src/main/java/org/locationtech/geowave/core/ingest/spark/SparkIngestDriver.java
core/store/src/main/java/org/locationtech/geowave/core/store/adapter/statistics/histogram/FixedBinNumericHistogram.java
examples/data/notebooks/jupyter/geowave-gdelt.ipynb
examples/data/notebooks/jupyter/geowave-gpx.ipynb
test/src/main/java/org/locationtech/geowave/test/HBaseMiniClusterClassLoader.java
test/src/main/java/org/locationtech/geowave/test/services/grpc/GeoWaveGrpcTestClient.java
test/src/main/java/org/locationtech/geowave/test/spark/SparkTestEnvironment.java
test/src/test/java/org/locationtech/geowave/test/services/grpc/GeoWaveGrpcIT.java
test/src/test/java/org/locationtech/geowave/test/spark/GeoWaveJavaSparkIT.java
test/src/test/java/org/locationtech/geowave/test/spark/GeoWaveJavaSparkKMeansIT.java
test/src/test/java/org/locationtech/geowave/test/spark/GeoWaveJavaSparkSQLIT.java
test/src/test/java/org/locationtech/geowave/test/spark/GeoWaveSparkSpatialJoinIT.java

Creating pull request for now, still waiting on failure from Travis to ensure thrown exception behaves as expected.

Beckerr spark and histogram fix

---

core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseQuery.java
core/store/src/main/java/org/locationtech/geowave/core/store/memory/MemoryDataStoreOperations.java
core/store/src/main/java/org/locationtech/geowave/core/store/memory/MemoryFactoryHelper.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/BaseReaderParams.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/BaseReaderParamsBuilder.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/DataStoreOperations.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/ReaderParams.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/ReaderParamsBuilder.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/RowDeleter.java
core/store/src/main/java/org/locationtech/geowave/core/store/operations/remote/MergeDataCommand.java
core/store/src/main/java/org/locationtech/geowave/core/store/util/DataStoreUtils.java
core/store/src/main/java/org/locationtech/geowave/core/store/util/MergingEntryIterator.java
core/store/src/main/java/org/locationtech/geowave/core/store/util/RewritingMergingEntryIterator.java
extensions/cli/landsat8/src/main/java/org/locationtech/geowave/format/landsat8/RasterIngestRunner.java
extensions/cli/sentinel2/src/main/java/org/locationtech/geowave/format/sentinel2/RasterIngestRunner.java
extensions/datastores/accumulo/src/main/java/org/locationtech/geowave/datastore/accumulo/operations/AccumuloOperations.java
extensions/datastores/accumulo/src/main/java/org/locationtech/geowave/datastore/accumulo/operations/AccumuloRowDeleter.java
extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraDeleter.java
extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraOperations.java
extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/operations/DynamoDBDeleter.java
extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/operations/DynamoDBOperations.java
extensions/datastores/hbase/src/main/java/org/locationtech/geowave/datastore/hbase/operations/HBaseOperations.java
extensions/datastores/hbase/src/main/java/org/locationtech/geowave/datastore/hbase/operations/HBaseRowDeleter.java
test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveBasicRasterIT.java

Make mergedata cli command synchronous.
Add client side mergedata support.

Update mergeData support.

---

core/mapreduce/src/main/java/org/locationtech/geowave/mapreduce/JobContextAdapterIndexMappingStore.java
core/mapreduce/src/main/java/org/locationtech/geowave/mapreduce/JobContextIndexStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/adapter/AdapterIndexMappingStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/index/IndexStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/memory/MemoryIndexStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/metadata/AdapterIndexMappingStoreImpl.java
core/store/src/main/java/org/locationtech/geowave/core/store/metadata/IndexStoreImpl.java

Added necessary implementations for removal of indices and types and also copyTo methods. Work should perform all required house keeping duties as well. This PR addresses issue #1440.

Added implementations for DataStore removal and copy methods.

---

core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStore.java
core/store/src/main/java/org/locationtech/geowave/core/store/memory/MemoryDataStoreOperations.java
core/store/src/test/java/org/locationtech/geowave/core/store/api/DataStoreTest.java

Unit tests for:
- `test addType(DataTypeAdapter<T> dataTypeAdapter, Index... initialIndices)`
- `addIndex(String typeName, Index... indices)`
- `createWriter(String typeName)`

Unit tests for DataStore API

---

extensions/datastores/cassandra/src/test/Java/org/locationtech/geowave/datastore/cassandra/CassandraOptionsTest.java
extensions/datastores/cassandra/src/test/Java/org/locationtech/geowave/datastore/cassandra/CassandraRequiredOptionsTest.java
extensions/datastores/cassandra/src/test/Java/org/locationtech/geowave/datastore/cassandra/CassandraRowTest.java

Added unit tests for config functions in Cassandra datastore

Unit test for Cassandra datastore

---

extensions/datastores/redis/pom.xml
extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/util/AbstractRedisSetWrapper.java
extensions/datastores/redis/src/test/java/org/locationtech/geowave/datastore/redis/util/RedisScoredSetWrapperTest.java
extensions/datastores/redis/src/test/java/org/locationtech/geowave/datastore/redis/util/RedisUtilsTest.java

- Fix NPE when flushing synchronous RedisScoredSetWrapper
- Simplify dependency for Arrays utility

Add unit tests for RedisScoredSetWrapper

---

.travis.yml

Use xenial (ubuntu 16.04) for Travis environment

---

python/src/main/python/pygw/__init__.py
python/src/main/python/pygw/base_models.py
python/src/main/python/pygw/config.py
python/src/main/python/pygw/debug.py
python/src/main/python/pygw/indices.py
python/src/main/python/pygw/query.py
python/src/main/python/pygw/sft_example.py
python/src/main/python/pygw/stores.py

- Relative python imports -> absolute
- Added some code stubs
- Starter Implementation for query

Query & small fixes

---

python/src/main/python/pygw/config.py
python/src/main/python/pygw/query.py

Added initial support for cql queries.

CQL Query support

---

python/src/main/python/pygw/__init__.py
python/src/main/python/pygw/base_models.py
python/src/main/python/pygw/query.py
python/src/main/python/pygw/statistics_query.py

Signed-off-by: Aaron Bu <acb256@cornell.edu>

copy_to and delete_all, documentation

---

python/src/main/python/pygw/config.py
python/src/main/python/pygw/sft_example.py

Signed-off-by: Alexander Greenberg <agg73@cornell.edu>

Simple Feature implementation

---

extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduDataIndexRead.java
extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduOperations.java
extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduRangeRead.java
extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduReader.java
extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/util/AsyncClientPool.java

* async reader
* style improving
Signed-off-by: cyzhan1118 <cz336@cornell.edu>

async reader (#30)

---

extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/adapter/RasterDataAdapter.java

Signed-off-by: Byunghwa Yun ombine@combineads.co.kr

Removed unnecessary duplicate code

---

core/cli/src/main/java/org/locationtech/geowave/core/cli/utils/ConsolePrinter.java
core/cli/src/main/java/org/locationtech/geowave/core/cli/utils/FirstElementListComparator.java
core/store/src/main/java/org/locationtech/geowave/core/store/cli/store/DescribeStoreCommand.java
core/store/src/main/java/org/locationtech/geowave/core/store/cli/store/ListStoresCommand.java
core/store/src/main/java/org/locationtech/geowave/core/store/cli/store/StoreOperationProvider.java
extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/query/ConsoleQueryOutputFormat.java

Signed-off-by: jhickman <jhickman@prominentedge.com>

Add ListStore and DescribeStore commands; genericize console output

---

core/index/src/main/java/org/locationtech/geowave/core/index/IndexUtils.java
extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/adapter/RasterDataAdapter.java
extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/util/DataBufferPersistenceUtils.java
extensions/formats/geotools-raster/pom.xml
extensions/formats/geotools-raster/src/main/java/org/locationtech/geowave/format/geotools/raster/GeoToolsRasterDataStoreIngestPlugin.java

Added support for NetCDF along with some basic fixes discovered while debugging NetCDF sample files.

fixes to support example netcdfs

---

core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStore.java
test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveCustomIndexIT.java

This PR addresses #1655.  The issue was due to an incorrectly cached scan callback.

Fix issue with cached scan callback

---

core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStore.java

Fix issue with deleting when using secondary indexing.

---

pom.xml

2 days ago they took down the repo's we reference in our pom (so I assume all builds will be failing until this fix).  The guidance is to switch to these osgeo repos: https://github.com/geotools/geotools/wiki/Change-from-webdav-to-nexus-repository

updated pom to use osgeo maven repo

---

extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemIndexTable.java

Signed-off-by: Rich Fecher <rich.fecher@blacklynx.tech>

filesystem datastore bug fix in formatting index values

---

core/store/src/main/java/org/locationtech/geowave/core/store/base/BaseDataStore.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/config/RocksDBOptions.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/operations/RocksDBOperations.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/util/AbstractRocksDBTable.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/util/RocksDBClient.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/util/RocksDBClientCache.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/util/RocksDBDataIndexTable.java
extensions/datastores/rocksdb/src/main/java/org/locationtech/geowave/datastore/rocksdb/util/RocksDBIndexTable.java

removes the read-only DB instance for simplicity

Use a single instance of rocksdb

---

.github/workflows/publish.yml
.github/workflows/test.yml
README.md
deploy/scripts/clean-up.py

fixed an issue with s3 cleanup script

---

.github/workflows/test.yml
deploy/scripts/clean-up.py

workflow improvement

---

.github/workflows/test.yml
.utility/run-tests.sh
README.md
deploy/Jenkinsfile
deploy/packaging/docker/build-src/build-geowave-common.sh
deploy/packaging/docker/build-src/build-geowave-vendor.sh
deploy/packaging/docker/docker-build-rpms.sh
deploy/packaging/emr/template/geowave-install-lib.sh.template
deploy/scripts/clean-up.py
test/src/main/java/org/locationtech/geowave/test/spark/SparkUtils.java

minor fix to jenkins

---

.github/workflows/test.yml
.utility/retry
test/src/test/java/org/locationtech/geowave/test/secondary/BasicSecondaryIndexIT.java
test/src/test/java/org/locationtech/geowave/test/secondary/MapReduceSecondaryIndexIT.java

added retries to get consistent test results

---

.github/workflows/publish.yml
.utility/publish-artifacts.sh
deploy/packaging/emr/template/geowave-install-lib.sh.template
test/src/test/java/org/locationtech/geowave/test/secondary/MapReduceSecondaryIndexIT.java

fixed an issue with publishing releases

---

docs/content/devguide/010-development-setup.adoc
docs/content/geowave-index/js/versions.js

Also fixes a formatting error in the developer guide

Fix missing 1.2.0 version in dropdown

---

core/index/src/main/java/org/locationtech/geowave/core/index/IndexPersistableRegistry.java
core/index/src/main/java/org/locationtech/geowave/core/index/VarintUtils.java
core/index/src/main/java/org/locationtech/geowave/core/index/text/EnumIndexStrategy.java
core/index/src/main/java/org/locationtech/geowave/core/index/text/EnumSearch.java
test/src/test/java/org/locationtech/geowave/test/GeoWaveITSuite.java
test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveEnumIndexIT.java
test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveTextIndexIT.java

GEOWAVE-1787: enumerated field indexing support

---

docs/content/devguide/010-development-setup.adoc

Updates the developer documentation.
Also, creates a baseline for integration tests.

Update development setup document
