packaging/puppet/geowave/manifests/accumulo.pp, packaging/puppet/geowave/manifests/app.pp, packaging/puppet/geowave/manifests/init.pp, packaging/puppet/geowave/manifests/params.pp, packaging/puppet/geowave/manifests/repo.pp, packaging/puppet/geowave/manifests/server.pp, packaging/puppet/geowave/manifests/service.pp, packaging/puppet/geowave/templates/jetty.xml.erb, packaging/rpm/admin-scripts/jenkins-build-geowave.sh, packaging/rpm/centos/6/.gitignore, packaging/rpm/centos/6/SPECS/geowave.spec, packaging/rpm/centos/6/rpm.sh
For ease of distribution and updating we'll package the GeoWave Puppet scripts and make them available as an RPM. Many folks will just want to extract the scripts from our tarball archive and manage themselves in their SCM (which is fine) Other projects may want or require (Red Disk) that Puppet scripts are managed via RPM.
=> Manage Puppet scripts within GeoWave project and package as an RPM

docs/content/086-puppet.adoc, docs/content/packages.html, packaging/rpm/admin-scripts/jenkins-build-geowave.sh
This patch does the following:
* Fixes the path issue when packaging the puppet scripts in jenkins-build-geowave.sh
* Updates the list of rpms available to include the geowave-puppet rpm
* Adds a documentation page showing examples of how to configure geowave using the puppet module
=> Add puppet doc page and fix archive path error that broke build

packaging/rpm/centos/6/SPECS/geowave.spec
This patch removes more of the GeoServer default config to get rid of the demo data. The orphaned layergroup config files were causing layer previews to fail.
=> Fixes layer preview bug by removing layergroup config files

docs/.gitignore, docs/content/000-titlepage.adoc, docs/content/050-framework.adoc, docs/content/060-ingestplugins.adoc, docs/content/manpages/geowave-ingest-clear.adoc, docs/content/manpages/geowave-ingest-hdfsingest.adoc, docs/content/manpages/geowave-ingest-hdfsstage.adoc, docs/content/manpages/geowave-ingest-localingest.adoc, docs/content/manpages/geowave-ingest-poststage.adoc, docs/content/manpages/geowave-ingest.adoc, packaging/rpm/admin-scripts/jenkins-build-geowave.sh, packaging/rpm/centos/6/SPECS/geowave.spec
This patch does the following:
* Updates the app site links from a personal branch to the eventual location at ngageoint
* This commit _does not_ replace our current web site, that will be handled in a future cutover commit once everyone is happy with the state of the docs.
* Refactors the docs for the geowave-ingest command and creates manpages in addition the current HTML and PDF docs
* Extracts inline command docs and makes them into manpage docs
* During the RPM build process these manpages will be tranformed into text and included back into the HTML and PDF documentation
So one update location for geowave-ingest command documentation, the manpages, and the content will get included in all doc formats. 
The only caveat with this transformation process is if you create the docs locally …
=> Refactor geowave-ingest command docs so we can use for manpages as well

packaging/rpm/centos/6/SOURCES/deploy-geowave-to-hdfs.sh
So we can give developer groups permissions to update an entire directory we're going to store iterator jar files in /accumulo/classpath/APP_NAME. This patch uploads the geowave-accumulo.jar to /accumulo/classpath/geowave
=> Move the location of the geowave-accumulo.jar in HDFS

packaging/rpm/centos/6/SOURCES/deploy-geowave-to-hdfs.sh
I figured out using sudo -u was a problem with our locked down RedHat systems a while back but missed a line when refactoring this script last time.
Background in case anyone is interested in the details of the config issue: http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password
=> HDFS upload script should use su instead of sudo -u

packaging/rpm/admin-scripts/jenkins-build-geowave.sh, packaging/rpm/centos/6/SPECS/geowave.spec, packaging/rpm/centos/6/rpm.sh
A variety of path issues in the script kept this from building correctly and I forgot to add a build dependency to the RPM spec file. Sorry for the extra bother of another pull request but this should do it for the packaging of the HTML and PDF docs into the RPMs.
=> Fix various path issues and add RPM build requirement

docs/content/050-framework.adoc, docs/content/076-accumulo-config.adoc, docs/content/086-puppet.adoc, geowave-ingest/src/main/resources/geowave-ingest.sh, packaging/puppet/geowave/manifests/repo.pp
A number of tweaks to our install materials and docs following the most recent install activity.
* **Ingest script - geowave-ingest.sh**
* Use java -cp instead of java -jar now that we have more than 65k files in our jar
* **Puppet script - repo.pp**
* Make the default for GeoWave RPM repo config to be false
* **Doc updates**
* Update Accumulo classpath config example to use wildcard instead of a specific file name and other minor content clarifications
=> A number of tweaks to our install materials and docs

docs/content/manpages/geowave-ingest-clear.adoc, docs/content/manpages/geowave-ingest-clear.txt, docs/content/manpages/geowave-ingest-hdfsingest.adoc, docs/content/manpages/geowave-ingest-hdfsingest.txt, docs/content/manpages/geowave-ingest-hdfsstage.adoc, docs/content/manpages/geowave-ingest-hdfsstage.txt, docs/content/manpages/geowave-ingest-localingest.adoc, docs/content/manpages/geowave-ingest-localingest.txt, docs/content/manpages/geowave-ingest-poststage.adoc, docs/content/manpages/geowave-ingest-poststage.txt, docs/content/manpages/geowave-ingest.adoc, docs/content/manpages/geowave-ingest.txt, packaging/rpm/admin-scripts/jenkins-build-geowave.sh, packaging/rpm/centos/6/SPECS/geowave.spec, packaging/rpm/centos/6/rpm.sh
This commit will fix the generation of man pages and keep the source documentation in a single location.
All man page text is now in a single file per command, with all the manpage only markup escaped so other formats can safely include the content. The escaping tokens are removed before transformation into manpages and provided as an archive to the RPM process to simplify that build a bit as well.
=> Refactor man page generation

pom.xml
Addresses ticket #271 which updates the sonar plugin to a version recent enough to work with the newly released Sonar v5 server and disabled JavaDoc doclint checks which now throw errors when run under Java 1.8 instead of warnings.
=> Sonar plugin version and java doc lint

docs/content/085-accumulo-config.adoc, packaging/rpm/centos/6/SOURCES/deploy-geowave-to-hdfs.sh
After my recent goof with matching versions I was trying to think of a slightly faster way to check a tablet server. 
The RPM could upload the build.properties file we already install into the local file system along with the iterator jar into hdfs so we could more easily verify what's in hdfs using hadoop fs -cat (no need to unzip anything). This combined with some suggested one-liners in the docs would allow us to compare hdfs to the locally downloaded vfs jars.
=> Accumulo iterator versioning docs

geowave-analytics/src/main/java/mil/nga/giat/geowave/analytics/clustering/CentroidManagerGeoWave.java, geowave-vector/src/main/java/mil/nga/giat/geowave/vector/adapter/FeatureCollectionDataAdapter.java, geowave-vector/src/main/java/mil/nga/giat/geowave/vector/adapter/FeatureDataAdapter.java, geowave-vector/src/test/java/mil/nga/giat/geowave/vector/utils/QueryIndexHelperTest.java, pom.xml
Other files are formatting auto-changes; only real change here is to the pom.xml
Added the following S3 based maven repos for geowave:
```
<distributionManagement>
<repository>
<id>geowave-maven-releases</id>
<name>GeoWave AWS Release Repository</name>
<url>s3://geowave-maven/release</url>
</repository>
<snapshotRepository>
<id>geowave-maven-snapshots</id>
<name>GeoWave AWS Snapshot Repository</name>
<url>s3://geowave-release/snapshot</url>
</snapshotRepository>
</distributionManagement>
```
mvn deploy will now push to releases or snapshots (based on if ${project.version} contains "SNAPSHOT" in the string).
The repo is publicly viewable, but in order to publish you need the access keys - you can put them in your ~/.m2/settings.xml - here is the skeleton fragment:
```
<servers>
<server> …
```
=> Added deploy to S3 option+repo

.utility/changelog-generator.sh, .utility/push-javadoc-to-gh-pages.sh, README.md, docs/content/050-framework.adoc, docs/content/075-install-from-rpm.adoc, docs/content/080-install-from-source.adoc, docs/content/100-documentation.adoc, docs/content/105-puppet.adoc, docs/content/packages.html
* Package download page in S3 replaced with a redirect to github.io page and updated existing doc references
* Fixed http(s) problem with download page, works with either now
* Additional explanation for -localingest Accumulo namespace argument
* Updated outdated build from source instructions referencing geowave-deploy directory
* Added some info about our new -P vendor profile build flag
* Removed Travis documentation generation restriction requiring JDK7
=> Download page and documentation updates

docs/content/000-titlepage.adoc, docs/content/075-install-from-rpm.adoc, packaging/rpm/admin-scripts/jenkins-build-rpm.sh
* Extract documentation.pdf from site archive within our tarball distribution so it's more obvious
* Copy documentation.pdf to S3 if aws command is availble
* Link to pdf from our docs
* I added a docs directory to our geowave S3 bucket and added a policy that makes everything public
* Worked around an Asciidoc formatting bug where the end of one section uses a formatting construct like a list or a table and it does not correctly recognize the next section marker. I changed a bullet list into two paragraphs
=> Publish PDF to S3 if available

packaging/rpm/admin-scripts/default-props.sh
I had to recreate the jenkins server in AWS to have it pick up an IAM role so the IP changed. This change will have it use hostname until such time as this setting goes away and we just start using public S3 buckets instead of jenkins for most of our artifacts.
=> Update Jenkins URL to use hostname instead of IP

core/cli/src/main/resources/geowave-tools-cmd-completion.sh, core/cli/src/main/resources/geowave-tools.sh, deploy/packaging/puppet/geowave/manifests/accumulo.pp, deploy/packaging/puppet/geowave/manifests/app.pp, deploy/packaging/puppet/geowave/manifests/init.pp, deploy/packaging/puppet/geowave/manifests/params.pp, deploy/packaging/puppet/geowave/manifests/server.pp, deploy/packaging/rpm/admin-scripts/jenkins-build-geowave.sh, deploy/packaging/rpm/admin-scripts/jenkins-build-rpm.sh, deploy/packaging/rpm/admin-scripts/rpm-functions.sh, deploy/packaging/rpm/centos/6/SOURCES/bash_profile.sh, deploy/packaging/rpm/centos/6/SOURCES/deploy-geowave-to-hdfs.sh, deploy/packaging/rpm/centos/6/SPECS/geowave.spec, deploy/packaging/rpm/centos/6/rpm.sh, deploy/src/main/resources/build.properties
This is hopefully all the changes needed to update all the Jenkins builds and do a final install test on both Cloudera and Hortonworks. The final commit before declaring the 0.8.7 final release will contain the updated documentation.
* core, docs and puppet rpms are no longer vendor prefixed
* All other rpms now have geowave and version in the name ex: geowave-0.8.7-hdp2 to support concurrent vendor and version installs
* Using the Linux alternatives utility only one install will be active
* Puppet scripts updated to use new RPM names
* Updated Jenkins build scripts
=> Build, packaging and deployment updates for 0.8.7 refactor

core/store/src/main/java/mil/nga/giat/geowave/core/store/DataStore.java, core/store/src/main/java/mil/nga/giat/geowave/core/store/query/QueryOptions.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/AccumuloDataStore.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloFilteredIndexQuery.java, test/src/test/java/mil/nga/giat/geowave/test/GeoWaveITSuite.java, test/src/test/java/mil/nga/giat/geowave/test/query/AttributesSubsetQueryIT.java
Initial stab at #143 including Integration Test to demonstrate approach and results.  Feedback welcome!
I added a new query method to the DataStore that allows one to provide a desired subset of attributes to be included in query results.  Research into available iterators to accomplish this goal within the tablets led me to `ColumnQualifierFilter` and [this discussion](http://apache-accumulo.1065345.n5.nabble.com/ColumnQualifierFilter-td1580.html), which recommends leveraging `scanner.fetchColumn(Text colFam, Text colQual)` for this purpose.
The integration test ingests sample data for the 10 largest cities in the US (city, state, population, land area, coordinates) and demonstrates 3 queries against this data set.  Each query constructs a bounding box designed to match 3 cities from …
=> GEOWAVE-143

pom.xml
One of the causes of our repo bloat was the javadocs constantly changing due to a generated timestamp. The configuration seems to have no effect when set within the aggregate/site phase but works as a global setting.
=> Stop adding timestamp to javadocs html

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/utils/GeometryUtils.java, extensions/formats/geolife/src/main/java/mil/nga/giat/geowave/format/geolife/GeoLifeIngestPlugin.java
Fix for #53 
Geolife dataset contains a single coordinate (see below) that was causing wrap-around issues.  
```
Finished analyzing 24876978 coordinates from the Geolife dataset
Total execution time: 29 seconds
Found 1 problematic coordinates:
latitude = 400.166666666667, longitude = 116.21539 (line 6782 of file C:\Users\yeagerdc\Desktop\Geolife Trajectories 1.3\Data\020\Trajectory\20110911000506.plt)
```
=> Geolife Ingest handling of bad coordinates

docs/content/085-accumulo-config.adoc, docs/content/105-puppet.adoc
Fixed a yum command and added a handy one-liner to figure out what iterators have been configured.
```
[spohnae@c1-app-02 ~]$ accumulo shell -u root -p ROOT_PWD -e "config -np" | grep -A 1 general.vfs.contex
t.classpath                                                                                          
site       | general.vfs.context.classpath.geolife .................. | 
system     |    @override ........................................... | hdfs://c1-master.ec2.internal:8020/accumulo/classpath/geowave/geowave-accumulo.jar
site       | general.vfs.context.classpath.geotools ................. | 
system     |    @override ........................................... | hdfs://c1-master.ec2.internal:8020/accumulo/classpath/geowave/geowave-accumulo.jar
site       | …
```
=> Corrected one command and added a tip on inspecting configs

deploy/packaging/rpm/centos/6/SOURCES/geowave-init.sh, deploy/packaging/rpm/centos/6/SPECS/geowave.spec
This will allow us to add GeoServer configs like Xmx2g on an app server node in an external file either manually or with something like Puppet. This will preserve the setting between upgrades and will not modify any RPM installed files.
=> Source config file if present for GeoServer setttings

deploy/packaging/rpm/centos/6/SOURCES/deploy-geowave-to-hdfs.sh, docs/content/075-install-from-rpm.adoc
Addresses issue #423 and will add one additional HDFS user to the list of default usernames array. If a custom user we'll never be able to guess was used add a --user argument to the script so it doesn't have to be modified when re-run manually.
=> Support CDH single user install

core/geotime/src/main/java/mil/nga/giat/geowave/core/geotime/store/filter/SpatialQueryFilter.java, extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/transaction/ZooKeeperTransactionAllocaterTest.java
The new approach also adds an optimization for the use of Interning geometries.  The prior approach lead to excessive memory use due to the reconstitution of geometry PRIOR to interning, creating unnecessary duplicates.
=> Issue #425 Optimize spatial queries to use prepared geometries.

docs/content/090-building.adoc, docs/pom.xml
* Updated version of asciidoc ruby libs fix the problem that used to prevent the inclusion of images when  the docs were built on a Windows host
* Added note that GeoWave requires Maven >= 3.2.1 to build due to the use of wildcard dependency exclusions
=> Update asciidoc lib versions

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveGTDataStoreFactory.java
Addresses #439 
Issue was an unnecessary LOGGER.error() statement in the catch block of a checked Exception that is actually being handled properly.
=> Cleaned up unnecessary logging of checked Exception that is handled properly

core/cli/src/main/resources/geowave-tools.sh
Pick up java system properties in the geowave tools script if they've been set in an environment var.
Example: 
export GEOWAVE_TOOL_JAVA_OPT=-DSIMPLE_FEATURE_CONFIG_FILE=myconfigfile.json
geowave -localingest ...
=> Pick up java system properties if set

core/index/src/main/java/mil/nga/giat/geowave/core/index/CompoundIndexStrategy.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/CompoundIndexStrategyTest.java
Implemented CompoundIndexStrategy. For now it allows the
composition of two NumericIndexStrategy objects into a
single NumericIndexStrategy. This can easily be modified
to support N sub-indeces. The dimensions of the
CompoundIndexStrategy are the sum of the dimensions of
the sub-indeces. The compound index prefixes the bytes
from the first sub-index before any of the bytes from the
second. Externally, the compound index can be treated like
any other multi-dimensional index.
=> Implemented a Compound Index Strategy

core/index/src/main/java/mil/nga/giat/geowave/core/index/CompoundIndexStrategy.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/CompoundIndexStrategyTest.java
CompoundIndexStrategy now has a noargs constructor. This
is necessary for PersistenceUtils to deserialize the strategy.
Also, changed the getId method to return the hashcode. This is
what other NumericIndexStraty implementations do.
=> Fixed persistence of CompoundIndexStrategy

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/AbstractIngestCommandLineDriver.java
Per @ewilson-radblue:
Addresses #464 (I suppose creating that issue wasn't necessary).
The problem was when using fields specified in an IngestFormatOptionProvider from a plugin. In AbstractIngestCommandLineDriver, it tries to parse the command on line 108 but does not call IngestFormatOptionProvider's applyOptions() method until it calls getPluginProviders() on line 141. It would try to reparse the command on line 162 with the additional options, but the failed parse on line 108 throws an exception and never gets to that line. Also, if the 'f' flag is not specified, the custom options are never added at all.
The fix is to set the parameter 'stopAtNonOption' to 'true' for CommandLineParser.parse() so that it doesn't throw an exception on an unrecognized parameter. This allows it to pull …
=> Geowave 464

core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder/IntegerLexicoder.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder/Lexicoders.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder/LongLexicoder.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder/NumberLexicoder.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/lexicoder/ShortLexicoder.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/simple/SimpleIntegerIndexStrategy.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/simple/SimpleLongIndexStrategy.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/simple/SimpleNumericIndexStrategy.java, core/index/src/main/java/mil/nga/giat/geowave/core/index/simple/SimpleShortIndexStrategy.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/lexicoder/IntegerLexicoderTest.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/lexicoder/LongLexicoderTest.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/lexicoder/ShortLexicoderTest.java, core/index/src/test/java/mil/nga/giat/geowave/core/index/simple/SimpleNumericIndexStrategyTest.java
This is an implementation of a simple 1-dimensional NumericIndexStrategy for indexing integer values. Can index keys of different sizes by using the appropriate lexicoder (short, int, or long are currently implemented). This index strategy will not work well for range insertions. See commit comments for more detail.
=> Implemented a Simple NumericIndexStrategy

extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/AbstractFieldRetypingSource.java, extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/RetypingVectorDataPlugin.java, extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/SimpleFeatureGeoWaveWrapper.java, extensions/formats/geotools-vector/src/main/java/mil/nga/giat/geowave/format/geotools/vector/retyping/date/DateFieldRetypingSource.java
See #492 
Grants RetypingVectorDataSource more control over the feature being retyped.  Existing logic was moved to AbstractFieldRetypingSource and existing implementations can simply inherit from that abstract class instead.
=> Allow for more dynamic SimpleFeature Retyping

.gitignore
Trivial .gitignore file update to disregard .DS_Store files in every direction on Mac OSX.
=> Added .DS_Store to .gitignore file for Mac OSX developers

deploy/packaging/rpm/admin-scripts/jenkins-build-geowave.sh
Only include plugin jars and not unrelated service jars into plugins.tar.gz archive that gets used by the RPM process.
=> Exclude service jars from getting packaged with plugins

deploy/packaging/puppet/geowave/manifests/app.pp, deploy/packaging/rpm/centos/6/SPECS/geowave.spec
A fix for #531 which will add the vendor version string to the documentation rpms so you'll easily be able to pick out a matched set of rpms for a given vendor install.
=> Make doc rpm vendor versioned

deploy/packaging/docker/.gitignore, deploy/packaging/docker/README.md, deploy/packaging/docker/build-args-matrix.sh.example, deploy/packaging/docker/build-rpm.sh, deploy/packaging/docker/docker-build-rpms.sh, deploy/packaging/docker/geowave-centos6-java7-build.dockerfile, deploy/packaging/docker/geowave-centos6-java8-build.dockerfile, deploy/packaging/docker/geowave-centos6-rpm-build.dockerfile, deploy/packaging/docker/pull-s3-caches.sh, deploy/packaging/rpm/admin-scripts/jenkins-build-geowave.sh, deploy/packaging/rpm/admin-scripts/rpm-functions.sh, deploy/packaging/rpm/centos/6/rpm.sh, docs/content/090-building.adoc
This commit lays the groundwork for a multi-step transition from building GeoWave using customized Jenkins worker AMIs to using generic build nodes with just Docker and git installed #371  This is step one which will put in place the configuration needed to be able to build the containers and scripts to orchestrate the build.
=> Build and RPM GeoWave components using Docker containers

pom.xml
Per their blog article at http://blog.geoserver.org/2015/09/29/new-repository-and-release-delay/ it looks like boundless has re-hosted their Maven repo.
=> Update Boundless maven repo

extensions/adapters/vector/pom.xml, extensions/adapters/vector/src/main/avro/AvroSimpleFeature.avsc, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroAttributeRowBuilder.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureAttributeHandler.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureDataAdapter.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureReader.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureWriter.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/FeatureDataAdapter.java, extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureDataAdapterTest.java
This new adapter is intented to serialize all the attributes of a SimpleFeature as a single object.  This is meant as an optimization when visibility is the same for all attributes of the feature.
Included is the avro schema to create the generated classes from chris bennights Import/Export project, these are necessary for avro serializing/deserializing the SimpleFeature.
=> Addition of AvroFeatureAdapter

extensions/formats/stanag4676/format/src/main/java/mil/nga/giat/geowave/format/stanag4676/IngestMessageHandler.java, extensions/formats/stanag4676/format/src/main/java/mil/nga/giat/geowave/format/stanag4676/Stanag4676EventWritable.java
This pull request fixes an issue with a track point's video info (pixel column, pixel row and frame number) when an image chip is not available.
Prior to this fix, none of the video information for a track point or motion point was being populated if an image chip was not available. The pixel row, pixel col and frame number was being stored in GeoWave as -1.
An NPE was being thrown and caught when the imageChip was not populated causing the population of the other fields to be bypassed.
=> Invalid video info when no image chip is available

README.md
Updated the dead links for Java Advanced Imaging and Java Image I/O in README file.  Closes GEOWAVE-581 issue.
=> GEOWAVE-581 - Updated README dead links

deploy/emr/4/bootstrap-geowave.sh, deploy/emr/4/geowave-install-lib.sh, docs/content/081-running-from-emr.adoc
This request contains fixes for #633, "GeoWave on EMR Fails During Bootstrap".  Copies of these files have already been placed in the GeoWave S3 bucket used by the Jenkins EMR launch script.
The first problem was http://apache.mirrors.tds.net/accumulo/ removed all of the Accumulo binary archive files except for the recently released 1.6.5 and 1.7.0 and we defaulted to 1.6.4 To fix I made ACCUMULO_DOWNLOAD_BASE_URL a setting that defaults to https://archive.apache.org/dist/accumulo which has both recent and past releases. We could also vendor our own copies somewhere else if artifacts disappearing or moving continues to be a problem.
The second problem was the URL to the RPM GPG signing key for the Apache BigTop repo was recently moved and the repo file I was curling into /etc/yum.repos.d …
=> Doc and deployment script fixes for EMR bootstrap failures

core/store/src/main/java/mil/nga/giat/geowave/core/store/query/QueryOptions.java, core/store/src/test/java/mil/nga/giat/geowave/core/store/query/QueryOptionsTest.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureReader.java, extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoToolsAttributesSubsetTest.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/AccumuloDataStore.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AbstractAccumuloRowQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloConstraintsQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloFilteredIndexQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/AccumuloRowIdsQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/FieldFilter.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/InputFormatAccumuloRangeQuery.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/QueryFilterIterator.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/query/SharedVisibilitySplittingIterator.java, extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/util/AccumuloUtils.java, test/src/test/java/mil/nga/giat/geowave/test/query/AttributesSubsetQueryIT.java
Fix for #615
SharedVisibilitySplittingIterator decomposes composite fieldIds on the tablet server, which replaces the old approach of doing this twice (once client side in AccumuloUtils and also in QueryFilterIterator)
FieldFilter filters only those fieldIds that were specified in QueryOptions
AttributesSubsetQueryIT tests both server side and client side filtering functionality
We also support subsetting through GeoTools Query via propertyNames.  GeoToolsAttributesSubsetTest verifies this functionality
=> Geowave 615

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/KafkaToGeowaveCommand.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToGeowaveCommand.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/LocalToMapReduceToGeowaveCommand.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/MapReduceToGeowaveCommand.java
Apparently I missed this.  If the index doesn't exist when they specify it on the command line, it will just ignore it and pass 0 indexes
=> GEOWAVE-546 - Throw exception if index doesn't exist

core/store/src/main/java/mil/nga/giat/geowave/core/store/GeoWaveStoreFinder.java
The registered families was not being instantiated unless manually done.  In DataStorePluginOptions, this is done for us, but it wouldn't be done under manual usage of GeoWaveStoreFinder.
=> GEOWAVE-727 - Fix issue introduced with this PR

analytics/api/src/main/java/mil/nga/giat/geowave/analytic/GeometryDataSetGenerator.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:S1118 - Utility classes should not have public constructors.
squid:S2293 - The diamond operator ("<>") should be used.
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S1481 - Unused local variables should be removed.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1197
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S2293
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCod …
=> multiple code improvements: squid:S1197, squid:S1118, squid:S2293, squid:CommentedOutCodeLine, squid:S1481, squid:UselessParenthesesCheck

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/kafka/IngestFromKafkaDriver.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/kafka/KafkaCommandLineOptions.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/KafkaToGeowaveCommand.java, core/store/src/main/java/mil/nga/giat/geowave/core/store/IngestCallbackList.java, test/src/main/java/mil/nga/giat/geowave/test/GeoWaveITRunner.java, test/src/main/java/mil/nga/giat/geowave/test/kafka/KafkaTestUtils.java, test/src/test/java/mil/nga/giat/geowave/test/GeoWaveITSuite.java, test/src/test/java/mil/nga/giat/geowave/test/kafka/BasicKafkaIT.java
For GEOWAVE #546: If a kafka properties file isn't selected, then it won't apply command line options to the kafka config properties.  Changed it so that it will do it whether the config file is specified or not.
For GEOWAVE #696: Fixed IndexCallbackList to implement Flushable, which will then allow the IndexWriter.flush() method to flush properly.  Also, modified IT tearDown code to work in reverse order.  For Kafka IT, it was tearing down Accumulo (with zookeeper) before tearing down kafka, and the kafka client was in an infinite loop trying to re-connect to zookeeper at the end of the IT.
Also, modified the BasicKafkaIT to not wait randomly 60 seconds, but instead to wait until all the data has been ingested, and the consumer times out before continuing the integration test.  This will …
=> GEOWAVE-546 & GEOWAVE-696 Fixes / Updates

core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/IngestOperationProvider.java, core/ingest/src/main/java/mil/nga/giat/geowave/core/ingest/operations/ListPluginsCommand.java, docs/content/050-ingest-example.adoc, docs/content/055-ingestplugins.adoc, docs/content/057-ingeststats.adoc
I didn't touch DBSCAN which is mentioned in #737 because I know @rwgdrummer and @datasedai are doing a scrub of the analytics documentation, but the other issues in the documentation are covered in this
=> GEOWAVE-737: update examples to use new 0.9.1 commandline syntax

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/FeatureDataAdapter.java
with multi-threaded ingest previous implementation has a race condition that can result in non-deterministic exceptions of this form:
java.lang.IllegalArgumentException: value already present: 29
at com.google.common.collect.HashBiMap.put(HashBiMap.java:246)
at com.google.common.collect.HashBiMap.put(HashBiMap.java:223)
at mil.nga.giat.geowave.adapter.vector.FeatureDataAdapter.initializePositionMaps(FeatureDataAdapter.java:710)
calling forcePut should at least circumvent this issue
=> fixed concurrency issue in position map

deploy/emr/4/gdelt-example/ingest-and-kde-gdelt.sh
Fixed a command that seems to have slipped through the cracks.  Format now matches expected command-line format.
=> Fixed KDE command to match 0.9.1 CLI format

extensions/formats/stanag4676/format/pom.xml, extensions/formats/stanag4676/service/pom.xml, extensions/pom.xml
xuggler is really only necessary for the 4676 webapp and should be pulled out as a dependency from the format regardless...and let's just for now make the webapp not part of the default build process because the maven repository hosting xuggler recently broke us
=> temporary fix for missing xuggler artifact

pom.xml
I was going through geowave-vagrant trying to update it, and this hook will be nice for maintenance of those scripts
=> GEOWAVE-798: can set final name of tools shaded jar on mvn commandline

extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/AvroFeatureUtils.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1854 - Dead stores should be removed.
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
=> multiple code improvements: squid:S1854, squid:S1118

extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/query/IndexOnlySpatialQuery.java
In this changeset, a default constructor is added to the `IndexOnlySpatialQuery` class.  Without such a constructor, attempting to perform a query using the `newAPIHadoopRDD`/`GeoWaveIngestFormat` mechanism[1] raises an exception[2].
1. 
```
sc.newAPIHadoopRDD(
config,
classOf[GeoWaveInputFormat[GridCoverage2D]],
classOf[GeoWaveInputKey],
classOf[GridCoverage2D]);
```
2.
```
at java.lang.Class.getConstructor0(Class.java:3082)
at java.lang.Class.getDeclaredConstructor(Class.java:2178)
at mil.nga.giat.geowave.core.index.PersistenceUtils.classFactory(PersistenceUtils.java:121)
at mil.nga.giat.geowave.core.index.PersistenceUtils.fromBinary(PersistenceUtils.java:91)
at mil.nga.giat.geowave.mapreduce.input.GeoWaveInputConfigurator.getQueryInternal(GeoWaveInputConfigurator.java:41)
at …
```
=> Add Default Constructor for IndexOnlySpatialQuery

extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/adapter/RasterDataAdapter.java, test/src/test/java/mil/nga/giat/geowave/test/GeoWaveRasterIT.java
It appears that the [length of raster metadata values](https://github.com/ngageoint/geowave/blob/56bf12867340c433b789b741e42b51c07c5405a5/extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/adapter/RasterDataAdapter.java#L1393) is currently being computed incorrectly.  The line `valueBinary = new byte[entryBinary.length - keyLength]` produces an array which is four bytes longer than the actual number of available bytes because the subtraction does not account for the length of the 32-bit integer which is also included in the entry.
That results in errors such as this:
```
Exception in thread "main" java.nio.BufferUnderflowException
at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
at java.nio.ByteBuffer.get(ByteBuffer.java:715)
at …
```
=> Fix: Computation of Raster Metadata Value Length

pom.xml
Use Maven Release Plugin to Increment Version Numbers on Release
To use (instructions also included in pom file above plugin):
mvn release:prepare
Version Number, Tag Name, and next Snapshot Name will need to be selected.  Sensible defaults matching our semantic versioning scheme are pre-populated.  Use -B to use default and run non-interactively.
Performs 3 actions:
- All pom files are updated with release version & pushed to repo
- repo is tagged
- All pom files are updated with next snapshot version
=> Add Release Plugin

.travis.yml
using travis-ci caching mechanism to speed-up builds
=> caching landsat scenes/images and gdal for travis-ci

analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/AccumuloKDEReducer.java, analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/GaussianCellMapper.java, analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDECommandLineOptions.java, analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDEJobRunner.java, analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/compare/ComparisonAccumuloStatsReducer.java, analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/compare/ComparisonStatsJobRunner.java, core/store/src/main/java/mil/nga/giat/geowave/core/store/operations/remote/options/DataStorePluginOptions.java, extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/RasterUtils.java, extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/adapter/RasterDataAdapter.java, extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/operations/options/RasterTileResizeCommandLineOptions.java, extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/resize/RasterTileResizeHelper.java, extensions/adapters/raster/src/main/java/mil/nga/giat/geowave/adapter/raster/resize/RasterTileResizeJobRunner.java, extensions/adapters/raster/src/test/java/mil/nga/giat/geowave/adapter/raster/RasterUtilsTest.java, test/src/test/java/mil/nga/giat/geowave/test/GeoWaveRasterIT.java, test/src/test/java/mil/nga/giat/geowave/test/mapreduce/KDERasterResizeIT.java
this allows for KDE to ignore the merging combiner and tile no data merge strategy altogether, simplifying the process, but does require a final step, reusing the raster resize command to finalize the output with the appropriately requested tile size
=> fixed KDE to tileSize 1 and added tile resize as post process

pom.xml
This could be arguable, considering all snapshot artifacts can be built directly from source?  We do have the release repository linked so it seems consistent to add the snapshot as well?
=> added geowave snapshot repository

.utility/run-tests.sh
`if [ "$TRAVIS_REPO_SLUG" == "ngageoint/geowave" ]; then` in .utility/run-tests.sh was causing Travis to skip execution of all tests on GeoWave forks
See: https://travis-ci.org/dcy2003/geowave/builds/173884588
=> Removed statement preventing execution of tests on forks

extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/DynamoDBClientPool.java, extensions/datastores/dynamodb/src/main/java/mil/nga/giat/geowave/datastore/dynamodb/DynamoDBOptions.java
Changes:
Added support for region. Now a AWS region can be specified
Made entrypoint optional.
If both are specified- region will be considered.
Added support for client configuration. Currently max number of http connections, protocol and cache response metadata is allowed.
Further support can be added easily, by modifying the "getClientConfig()" function.
=> Support for DynamoDB Options

analytics/mapreduce/src/main/java/mil/nga/giat/geowave/analytic/mapreduce/kde/KDEJobRunner.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/ExtractGeometryFilterVisitor.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/GeoWaveFeatureCollection.java, extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/query/cql/CQLQuery.java, extensions/adapters/vector/src/test/java/mil/nga/giat/geowave/adapter/vector/plugin/ExtractGeometryFilterVisitorTest.java, extensions/cli/landsat8/src/main/java/mil/nga/giat/geowave/format/landsat8/RasterIngestRunner.java
Fixed an issue to extract out correct geometry constraints and predicate when you have multiple geometric attributes inside a CQL expression
=> Extract only the specified geometry attribute

deploy/packaging/docker/build-rpm/build-rpm.sh, deploy/packaging/docker/build-src/build-geowave-common.sh, deploy/packaging/docker/build-src/build-geowave-vendor.sh, deploy/packaging/docker/docker-build-rpms.sh, deploy/packaging/docker/publish/publish-common-rpm.sh, deploy/packaging/docker/publish/publish-vendor-rpm.sh
Jenkins Jobs should now fail properly
=> Fixed docker fail not causing jenkins to fail issue

examples/data/notebooks/zeppelin/GDELT-Quick-Start.json, examples/data/notebooks/zeppelin/GeoWave-GPX-Demo.json
The --cqlFilter param was already in the notebook. I added the QuickStart steps to download and ingest GDELT data. NOTE: This is NOT tested yet. We should leave this PR open until Jon or I have a chance to run through it on EMR.
=> Add GDELT download & ingest to Zeppelin example

deploy/packaging/docker/publish/publish-common-rpm.sh, deploy/packaging/emr/template/bootstrap-jupyter.sh.template
Use geowave-notebooks instead of main geowave bucket. geowave-notebooks able to list objects.
=> Modifying bucket used for notebook examples

test/src/main/java/mil/nga/giat/geowave/test/kafka/KafkaTestEnvironment.java
BasicKafkaIT was using a simple File.delete() call for log cleanup, which does not work for a directory that's not empty. Changed it to apache commons FileUtils.deleteDirectory() call.
=> Fixed kafka log cleanup in BasicKafkaIT

deploy/packaging/docker/build-rpm/build-services-rpm.sh
Test for existence of the accumulo restservices file before trying to copy it.  Fixes issue where script would terminate prematurely and not genereate restservices or geoserver rpms.
=> Fix accumulo restservices war copy

.travis.yml, analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/GeoWaveSparkConf.java, analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/kmeans/KMeansRunner.java, analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/sparksql/SqlQueryRunner.java, analytics/spark/src/main/java/mil/nga/giat/geowave/analytic/spark/spatial/TieredSpatialJoin.java, extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/HBaseDataStore.java, test/src/main/java/mil/nga/giat/geowave/test/annotation/Environments.java, test/src/main/java/mil/nga/giat/geowave/test/spark/SparkTestEnvironment.java, test/src/test/java/mil/nga/giat/geowave/test/mapreduce/DBScanIT.java, test/src/test/java/mil/nga/giat/geowave/test/spark/GeoWaveJavaSparkIT.java, test/src/test/java/mil/nga/giat/geowave/test/spark/GeoWaveJavaSparkKMeansIT.java, test/src/test/java/mil/nga/giat/geowave/test/spark/GeoWaveJavaSparkSQLIT.java, test/src/test/java/mil/nga/giat/geowave/test/spark/GeoWaveSparkSpatialJoinIT.java
Add additional test annotations for new stores.
Removes use of HBaseSplitProvider, currently causing duplicate features to be loaded into RDDs for Spark.
=> Refactor SparkSession & SparkConf use.

services/rest/src/main/java/mil/nga/giat/geowave/service/rest/FileUploadResource.java
This change allows an external consumer of the REST API to submit files in a
batch and ingest them in a single shot as opposed to submitting a single
ingest job per file.
Currently `geowave ingest localToGw` only accepts a single file or a directory
as the source parameter.  Doing "batch" ingests by transferring files via
`/restservices/v0/fileupload` would require invoking `localToGw` once for
every file in the batch which seems like it would require extra bookkeeping to
track and merge the operation statuses.
Refer to G3-297
=> Enable batch correlation of uploaded files

services/rest/src/main/java/mil/nga/giat/geowave/service/rest/GeoWaveOperationServiceWrapper.java, services/rest/src/main/java/mil/nga/giat/geowave/service/rest/field/RequestParametersJson.java
An attempt to smooth out some of the edges around the REST API and how it handles parameter parsing, specifically:
- Fixes errors from unconverted assignments of primitive `Object[]` arrays to fields
- Improves error logging for diagnostics/troubleshooting
- Adds null checks for optional/missing parameters
=> REST services parameter handling enhancements

deploy/packaging/emr/generate-emr-scripts.sh, deploy/packaging/emr/template/jupyter/bootstrap-jupyter.sh.template, deploy/packaging/emr/template/jupyter/bootstrap-jupyterhub.sh.template, deploy/packaging/emr/template/jupyter/create-configure-kernel.sh.template, deploy/packaging/emr/template/jupyter/install-conda.sh, deploy/packaging/emr/template/jupyter/jupyterhub_config.py
Current deployment explanation:
Deployment modifies single jupyter server deployment (bootstrap-jupyter) while keeping that deployment option intact. My thought behind this was the single server deployment option still provides the quickest and easiest route for someone just trying to demo what geowave + jupyter is capable of with the least additional configuration needed. JupyterHub with GEOAxis seemed a more specific deployment route that wouldn't traditionally be used by common public users.
For JupyterHub:
Current deployment assumes GEOAxis OAuthenticator will be used along with ssl certificates. These settings are configured within the jupyterhub_config.py. JupyterHub is configured as a Upstart service and started when the bootstrapping is complete.  When JupyterHub starts it will …
=> Implement JupyterHub deployment with GEOAxis authentication

deploy/packaging/docker/build-src/build-geowave-common.sh, deploy/packaging/docker/publish/publish-common-rpm.sh, deploy/packaging/emr/template/jupyter/bootstrap-jupyter.sh.template, deploy/packaging/emr/template/jupyter/bootstrap-jupyterhub.sh.template, deploy/packaging/emr/template/jupyter/install-conda.sh
Also locks down versions of jupyterhub + oauthenticator.
If we want to lockdown all versions of python dependencies according to submitted swap requests. I can modify how python dependencies are installed to be more robust. I can create a `requirements.txt` file for python dependencies, which will be locked down to specific dependency versions and have each bootstrap install from that file. I just need to know all versions of python dependencies that were swap approved.
=> Update build steps for pyspark tarball

deploy/packaging/docker/publish/publish-common-rpm.sh, deploy/packaging/emr/template/jupyter/bootstrap-jupyter.sh.template, deploy/packaging/emr/template/jupyter/bootstrap-jupyterhub.sh.template
Band-aid solution to not being able to recursive copy from 'geowave/latest'. 
Long-term solution involving creating separate geowave-docs bucket outlined in scrumdo ticket: [G3-458](https://app.scrumdo.com/projects/story_permalink/1664464)
=> Change publish scripts to use geowave-notebooks

core/store/src/main/java/org/locationtech/geowave/core/store/adapter/LazyReadPersistenceEncoding.java, core/store/src/main/java/org/locationtech/geowave/core/store/callback/DuplicateDeletionCallback.java, core/store/src/main/java/org/locationtech/geowave/core/store/query/constraints/InsertionIdQuery.java, core/store/src/main/java/org/locationtech/geowave/core/store/util/DataStoreUtils.java, extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/CassandraRow.java, extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/BatchedRangeRead.java, extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraOperations.java, extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/util/CassandraUtils.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/DynamoDBRow.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/operations/DynamoDBReader.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/operations/DynamoDBWriter.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/util/DynamoDBUtils.java, test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveCustomIndexIT.java
There was a relatively minor issue simply when deleting from a custom index that was originally masked by issue #1655 and the multi-index deletion issues.  Added a test for the custom index query and deletion all by itself along with another test for deletion with the custom index, spatial, and spatial-temporal indices.  The commented line with the TODO still exists with the multi-index deletion bug, but this resolves simply deletion from the custom index.
=> fixed issue with deleting from custom index

extensions/formats/geotools-raster/pom.xml
This PR fixes the following error:
`Error while parsing JAI registry file "file:/Applications/GeoWave/lib/ingest-formats/gt-raster/imageio-ext-imagereadmt-1.1.25.jar!/META-INF/registryFile.jai" :
Error in registry file at line number #29
A descriptor is already registered against the name "ImageReadMT" under registry mode "rendered"`
It seems to have been caused by there being multiple instances of imageio-ext-imagereadmt.jar on the classpath.
=> Fix JAI Error on CLI

core/cli/src/main/java/org/locationtech/geowave/core/cli/prefix/JCommanderPrefixTranslator.java
JCommander changed the field names from m_field/m_method to field and method.  Using reflection with newer versions of jcommander in the classpath throws a runtime exception (and this is in the code path of some fundamental API calls like `GeoWaveStoreFinder.createDataStore()`).  It seems we can account for both potential field names as a backup to provide a bit more flexibility in this regard.
=> GEOWAVE-1674: flexibility to have newer versions of jcommander in classpath

deploy/pom.xml, dev-resources/pom.xml, dev-resources/src/main/resources/assemblies/default-installer-plugin.xml, extensions/formats/geotools-raster/pom.xml, pom.xml
There was an exclusion in the installer plugin assembly profile for `gt-coverage`, which was causing `gt-coverage-api` to get excluded, which was a dependency needed by gt-netcdf.  I updated the exclusion to be more specific, and also added some more exclusions to reduce the number of duplicated dependencies in the installed geotools raster plugin.
=> Fix issues with missing NetCDF dependencies

.travis.yml, .utility/publish.sh
Also updates the publish logic to not have to clone the entire gh-pages history (~1.3 GB).
=> Fix incorrect dev resources version

core/index/src/main/java/org/locationtech/geowave/core/index/ByteArrayUtils.java, docs/content/devguide/075-programmatic-api.adoc, extensions/datastores/cassandra/src/main/java/org/locationtech/geowave/datastore/cassandra/operations/CassandraMetadataReader.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/operations/DynamoDBMetadataReader.java, test/src/test/java/org/locationtech/geowave/test/basic/AbstractGeoWaveBasicVectorIT.java, test/src/test/java/org/locationtech/geowave/test/docs/GeoWaveDocumentationExamplesIT.java
Fixes #1691 by performing client-side filtering on stat queries when a primary ID is supplied to the metadata query.
=> Fix incorrect stat queries on Cassandra and DynamoDB

extensions/datastores/redis/pom.xml, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/config/RedisOptions.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/operations/DataIndexRangeRead.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/operations/DataIndexRead.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/operations/RedisDataIndexWriter.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/operations/RedisOperations.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/operations/RedisReader.java, extensions/datastores/redis/src/main/java/org/locationtech/geowave/datastore/redis/util/RedisUtils.java, pom.xml
There are several github issues and stackoverflows referring to a memory leak when using FST with redisson. We were seriously running up against this issue and despite what this [1] says, the latest version does not simply resolve it. However, I figure it won't hurt to update to the latest version. We actually only use a provided serialization codec for the data index when secondary indexing is enabled - unfortunately that is our use case. As it stood GeoWave just always uses FST codec for that, which is Redisson's default codec. The only thing GeoWave is serializing for the data index is a `byte[]` so its very straightforward - I'm not sure the advantages/disadvantages of different codec when serializing an object as simple as an array of primitives. My first instinct was to just have …
=> updated redis version and provided serialization option

extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/config/DynamoDBOptions.java
The Regions enum serializes using toString() which is all uppercase and underscore separated but the Regions.fromValue() uses lower case and hyphen separators.
Signed-off-by: Rich Fecher <rich.fecher@blacklynx.tech>
=> fix for serialization of regions as enum

core/geotime/src/main/java/org/locationtech/geowave/core/geotime/util/ExtractGeometryFilterVisitor.java, docs/content/devguide/010-development-setup.adoc, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveFeatureCollection.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveFeatureReader.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/util/QueryIndexHelper.java, extensions/adapters/vector/src/test/java/org/locationtech/geowave/adapter/vector/plugin/GeoWaveFeatureReaderTest.java
Fixes #1702 and also handles cases where the geometry constraint is empty. Fixes a previously unknown bug with queries based on a temporal constraint only that broke depending on if the user issued the query with ECQL vs CQL. Added test for queries that only use temporal constraint to catch this issue in the future should it arise again. Also includes dev-guide update for debug configurations, fixing errors from pom.xml for plugin execution.
=> Fix for #1702, doc updates, and additional tests for GeoWaveFeatureReader

extensions/cli/dynamodb-embed/src/main/java/org/locationtech/geowave/datastore/dynamodb/cli/DynamoDBLocal.java, extensions/cli/dynamodb-embed/src/main/java/org/locationtech/geowave/datastore/dynamodb/cli/RunDynamoDBLocalOptions.java, extensions/datastores/dynamodb/src/main/java/org/locationtech/geowave/datastore/dynamodb/config/DynamoDBOptions.java, test/src/main/java/org/locationtech/geowave/test/DynamoDBStoreTestEnvironment.java
These are both extremely minor enhancements for using dynamodb.  One is just for launching the local instance, to be able to specify port seems like a pretty basic option you would want.  And the other is if region name is not null but is an empty string, it won't use endpoint (it just checks for null in the calling code of this Region, but it really shouldn't try to convert empty strings).  For example, we configure with spring YAML, and there's no way to unset a property  but you can set it to an empty string which seems like it should be sufficient to ignore "region."
=> a couple minor conveniences for dynamodb

extensions/adapters/vector/src/main/antlr4/org/locationtech/geowave/adapter/vector/query/gwql/parse/GWQL.g4, extensions/adapters/vector/src/test/java/org/locationtech/geowave/adapter/vector/query/gwql/SelectStatementTest.java
Fixes #1707. Update GWQL grammar to support unconventional type names. Added test for unconventional names as well.
=> GWQL grammar update for unconventional type names. Fixes #1707

docs/content/commands/manpages/raster/geowave-installgdal.txt, docs/content/quickstart-emr/quickstart-emr/020-raster-demo.adoc, docs/content/quickstart/015-raster-demo.adoc, extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/operations/InstallGdalCommand.java, extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/plugin/gdal/InstallGdal.java
Relates to #1684. Fixed installGdal to work on macOSX and install relative to proper geowave home directory on all OS's.
=> Fixes for installGdal command

extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/FileSystemDataFormatter.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemIndexTable.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/GeoWaveBinaryDataFormatter.java
just added "typeName" and "indexName" to one of the data formatter methods where it was missing.  The default binary formatter doesn't use type name or index name anywhere but its provided in every other method as just additional contextual info that can be helpful and used by the formatter as needed.  The Data Index formatter passes type name to every method and the Index formatter passes index name and type name to every method, again as potentially useful context for the formatter.
=> minor tweak to make format api more consistent

extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/FileSystemDataFormatter.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/FileSystemDataStoreFactory.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/config/FileSystemOptions.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemDataIndexWriter.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemOperations.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemQueryExecution.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemReader.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemRowDeleter.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/operations/FileSystemWriter.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemClient.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemClientCache.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemDataIndexTable.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemIndexTable.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/FileSystemUtils.java, extensions/datastores/filesystem/src/main/java/org/locationtech/geowave/datastore/filesystem/util/GeoWaveBinaryDataFormatter.java
needed to add a quick fix on line 152 of FileSystemOperations (one of the deleteAll methods didn't use subdirectory in creating the path).
So.. in addition to that small fix I did a little cleanup:
1) added `format` to the "client" so that it didn't need to be redundantly passed all over the place
2) allowed for directories supplied by the formatter plugin to be null or empty strings in which case it wouldn't add a subdirectory to the path.
3) allowed for the formatter to also define the directory of metadata (previously hard-coded to "metadata"
=> improved flexibility for directory naming

core/geotime/src/main/java/org/locationtech/geowave/core/geotime/store/query/aggregate/BoundingBoxAggregation.java, core/geotime/src/main/java/org/locationtech/geowave/core/geotime/store/query/aggregate/TimeRangeAggregation.java, core/store/src/main/java/org/locationtech/geowave/core/store/api/Aggregation.java, core/store/src/main/java/org/locationtech/geowave/core/store/query/aggregate/DataStatisticsAggregation.java, core/store/src/main/java/org/locationtech/geowave/core/store/query/aggregate/MergingAggregation.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/query/aggregation/CompositeVectorAggregation.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/query/aggregation/VectorCountAggregation.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/query/aggregation/VectorMathAggregation.java, extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/render/DistributedRenderAggregation.java
I know others are in this code so this may be more of a merge head-ache than its worth (take it or leave it), just a simple suggestion to clarify the to/from binary of aggregation based on @jdgarrett's recent comment.
=> added default to/from binary to aggregation

core/index/src/main/java/org/locationtech/geowave/core/index/text/EnumIndexStrategy.java
Apparently, the right thing to do for empty insertion IDs on a custom index strategy (ie. for invalid data) is to return an empty set of insertion IDs rather than null.
=> simple fix for enums as empty insertion IDs

core/geotime/src/test/java/org/locationtech/geowave/core/geotime/adapter/annotation/SpatialTemporalAnnotationsTest.java, core/geotime/src/test/java/org/locationtech/geowave/core/geotime/store/query/filter/expression/CQLToGeoWaveFilterTest.java, core/geotime/src/test/java/org/locationtech/geowave/core/geotime/store/query/filter/expression/SpatialTemporalFilterExpressionTest.java, core/store/src/main/java/org/locationtech/geowave/core/store/adapter/AbstractDataTypeAdapter.java, core/store/src/main/java/org/locationtech/geowave/core/store/adapter/BasicDataTypeAdapter.java, core/store/src/main/java/org/locationtech/geowave/core/store/adapter/SimpleAbstractDataAdapter.java, core/store/src/main/java/org/locationtech/geowave/core/store/index/AttributeDimensionalityTypeProvider.java, core/store/src/main/java/org/locationtech/geowave/core/store/index/AttributeIndexOptions.java, core/store/src/test/java/org/locationtech/geowave/core/store/TestStorePersistableRegistry.java, core/store/src/test/java/org/locationtech/geowave/core/store/adapter/AbstractDataTypeAdapterTest.java, core/store/src/test/java/org/locationtech/geowave/core/store/adapter/BasicDataTypeAdapterTest.java, core/store/src/test/java/org/locationtech/geowave/core/store/query/gwql/AbstractGWQLTest.java, examples/java-api/src/main/java/org/locationtech/geowave/examples/adapter/CustomAdapterExample.java, test/src/test/java/org/locationtech/geowave/test/query/ExpressionQueryIT.java
- Fix issues with the use of primitive types
- Allow the data ID field to be kept separate from the other fields so that they don't get serialized twice
- Allow the naming of attribute indices
- Allow no field descriptors to be supplied
- Update data ID serialization to use the field writer for the class instead of toString
- Fix stack overflow on SimpleAbstractDataAdapter
=> Fix issues and add improvements to basic data type adapters

README.md, core/mapreduce/src/main/java/org/locationtech/geowave/mapreduce/operations/CopyCommand.java, core/store/src/main/java/org/locationtech/geowave/core/store/cli/store/CopyStoreCommand.java, dev-resources/src/main/resources/assemblies/default-installer-plugin.xml, docs/content/commands/manpages/store/geowave-copy.txt, docs/content/commands/manpages/store/geowave-copymr.txt
Testing the log4j updates in the installer revealed the need to exclude the new log4j version to suppress the multiple binding warnings when using the installed version of GeoWave.
=> Various Updates
